# Generated by Django 3.2.7 on 2021-09-29 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_test_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='helminths',
            field=models.IntegerField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='lf',
            field=models.IntegerField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='oncho',
            field=models.IntegerField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='schisto',
            field=models.IntegerField(blank=True, max_length=200, null=True),
        ),
    ]
