# Generated by Django 3.2.7 on 2021-09-29 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20210929_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='helminths',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='lf',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='oncho',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='schisto',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
